# Generated by Django 3.2.5 on 2021-07-31 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speciality', models.CharField(choices=[('Family Physician', 'Family Physician'), ('Pediatrician', 'Pediatrician'), ('Obstetrician/Gynecologist', 'Obstetrician/Gynecologist'), ('Psychiatrist', 'Psychiatrist'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist')], default='', max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('picture', models.ImageField(upload_to='photos/hospitals/')),
                ('description', models.TextField(blank=True)),
                ('available_online', models.BooleanField(default=False)),
                ('available_person', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospitals.hospital')),
            ],
        ),
    ]
